# Generated by Django 5.2.1 on 2025-05-27 03:53

import learn.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', learn.models.CustomUserManager()),
            ],
        ),
    ]
